export const MASCOT_FEEDBACKS = {
    science: [
        "Every failed experiment is a step closer to the truth! 🔬",
        "Even Einstein had to revise his theories! Let's look again. 💡",
        "Hypothesis incorrect? That's just new data! Let's re-analyze. 📊",
        "The best discoveries often come from mistakes. Let's dig deeper! 🌱",
        "Biology, chemistry, physics... it's all about trial and error! 🧪",
        "Let's check our variables one more time! 🔍",
        "That didn't react the way we thought! Let's try another formula. 💥",
        "Great try! But let's observe the facts more closely. 👀",
        "Scientific progress requires patience! Let's rethink this. ⏳",
        "Let's put on our safety goggles and try again! 🥽",
        "The laws of physics say we can try again! ⚙️",
        "Let's peer through the microscope and find the error. 🔬",
        "Not quite the right reaction! Let's mix things up. 🧪",
        "Even the greatest scientists need a second attempt! 🔭",
        "Let's gather more evidence and try again. 📑",
        "A fascinating result, but not the correct one! Let's review. 🌟",
        "Let's re-examine our data points! 📉",
        "Every mistake is just a new scientific observation! 📝",
        "Let's recalibrate our instruments and go again! 📡",
        "The universe is full of mysteries, let's solve this one! 🌌",
        "Let's check the periodic table one more time! ⚛️",
        "Nature is tricky! Let's observe a bit closer. 🌿",
        "That's a hypothesis worth testing, but let's look at the facts! 🧠",
        "Let's spark a new idea and try this again! ⚡",
        "Science is about asking questions until we get the right answer! 🚀"
    ],
    math: [
        "Math is a puzzle, and every wrong piece helps us find the right one! 🧩",
        "Let's re-calculate! The logic is almost there. 🔢",
        "Even the best mathematicians double-check their work! 📐",
        "Equations can be tricky, but you've got this! ➕",
        "A tiny miscalculation! Let's solve it together. ✖️",
        "Let's break down the formula step by step. 📝",
        "Let's look at the numbers from a different angle! 📐",
        "Geometry, algebra, fractions... we'll conquer them all! 📏",
        "Let's subtract the error and add some focus! ➖",
        "Math is a language, let's read it carefully! 📖",
        "Let's plug the numbers back in and see what happens! 🔄",
        "Every problem has a solution, let's find it! 🎯",
        "Let's carry the one and try again! ➕",
        "Fractions can be dividing! Let's find a common denominator. ➗",
        "Let's multiply our effort and try once more! ✖️",
        "The proof is in the process! Let's review the steps. 📜",
        "Let's graph this out and see where we went off track. 📈",
        "Let's find the missing variable! 🔍",
        "Math requires precision! Let's measure twice and cut once. 📏",
        "Let's balance this equation together! ⚖️",
        "A calculation error is just a stepping stone to the right answer! 🧱",
        "Let's look for a pattern we might have missed! 🌀",
        "Let's trace our steps back to the beginning. 🔙",
        "Numbers don't lie, let's see what they're telling us! 🔢",
        "Let's crunch the numbers one more time! 💻"
    ],
    sst: [
        "History is full of mysteries! Let's uncover the facts. 🏺",
        "Every great explorer took a wrong turn sometimes. Let's find our map! 🗺️",
        "Let's review the timelines and civilizations. We'll get it! ⏳",
        "The globe is vast! Let's pinpoint exactly where we went wrong. 🌍",
        "Let's look back at the past to understand this better. 🏛️",
        "Let's check our historical sources again! 📜",
        "Geography can be tricky! Let's consult the compass. 🧭",
        "Let's navigate through these facts one more time. ⛵",
        "Empires rise and fall, and we can try again! 👑",
        "Let's dig up the truth like a true archaeologist! ⛏️",
        "Let's trace the trade routes and find the right answer. 🛤️",
        "Let's read the ancient texts more carefully! 📖",
        "The world is full of diverse cultures, let's learn about this one! 🌐",
        "Let's plot this on the map and see where it lands. 📍",
        "History teaches us to learn from our mistakes! 🎓",
        "Let's review the constitution and try again! 🏛️",
        "Let's travel back in time and re-examine the event! 🕰️",
        "Let's look at the societal impact one more time. 👥",
        "Geography is all about location, let's find the right spot! 🎯",
        "Let's uncover the layers of history together. 📚",
        "Every artifact tells a story, let's listen closely! 🏺",
        "Let's chart a new course to the correct answer! ⚓",
        "The past is a puzzle, let's fit the pieces together! 🧩",
        "Let's consult the archives and try again! 🗄️",
        "Our ancestors would want us to keep trying! 👨‍👩‍👧‍👦"
    ],
    english: [
        "Grammar is a journey! Let's review the rules. 📝",
        "Words can be tricky! Let's read that sentence again. 📖",
        "Even great authors need an editor. Let's revise! ✍️",
        "Let's look at the context clues one more time. 🔍",
        "A tiny typo or a misplaced modifier? Let's check! 🕵️",
        "Let's explore the vocabulary and find the right meaning! 📚",
        "Let's structure this paragraph a bit differently. 🏗️",
        "Let's read between the lines! 📖",
        "Every word has a purpose, let's find the right one! 🎯",
        "Let's unravel this sentence structure together! 🧶",
        "Let's look at the synonyms and antonyms. ↔️",
        "Let's polish our prose and try again! ✨",
        "Let's listen to the rhythm of the sentence. 🎵",
        "Punctuation matters! Let's check our commas. 💬",
        "Let's dive deeper into the character's motivation. 🎭",
        "Let's analyze the theme one more time. 🎨",
        "Let's spell it out and see where we went wrong. 🔤",
        "Let's craft a better response together! 🛠️",
        "Let's turn the page and try the next idea. 📄",
        "Language is an art form, let's refine our masterpiece! 🖼️",
        "Let's look for the hidden meaning in the text. 🧐",
        "Let's rewrite the narrative and get it right! 🖋️",
        "Let's find the perfect expression for this! 🎭",
        "Let's consult the dictionary and try again! 📕",
        "Every draft can be improved! Let's revise. 📋"
    ]
};
