-- MANYA DAILY CHALLENGES: Days 1-90
-- Run this in Supabase SQL Editor

INSERT INTO public.challenges (day_number, title, description, challenge_type, target_value, reward_type, reward_value, subject) VALUES
(1, 'First Steps', 'Answer 3 questions', 'CORRECT_ANSWERS', 3, 'gems', 5, 'all'),
(2, 'Keep Going', 'Answer 5 questions', 'QUESTIONS_ANSWERED', 5, 'gems', 5, 'all'),
(3, 'Math Starter', 'Get 3 math answers right', 'MATH_CORRECT', 3, 'gems', 8, 'math'),
(4, 'Science Spark', 'Get 3 science answers right', 'SCIENCE_CORRECT', 3, 'gems', 8, 'science'),
(5, 'Word Power', 'Get 3 English answers right', 'ENGLISH_CORRECT', 3, 'gems', 8, 'english'),
(6, 'History Buff', 'Get 3 SST answers right', 'SST_CORRECT', 3, 'gems', 8, 'sst'),
(7, 'Weekly Warmup', 'Complete 1 quest', 'QUEST_COUNT', 1, 'gems', 10, 'all'),
(8, 'Double Down', 'Answer 6 questions correctly', 'CORRECT_ANSWERS', 6, 'gems', 8, 'all'),
(9, 'No Hints!', 'Get 2 perfect answers', 'PERFECT_ANSWERS', 2, 'gems', 10, 'all'),
(10, 'Ten Day Hero', 'Answer 8 questions', 'QUESTIONS_ANSWERED', 8, 'gems', 10, 'all'),
(11, 'Math Focus', 'Get 5 math answers right', 'MATH_CORRECT', 5, 'gems', 10, 'math'),
(12, 'Lab Day', 'Get 5 science answers right', 'SCIENCE_CORRECT', 5, 'gems', 10, 'science'),
(13, 'Grammar Time', 'Get 5 English answers right', 'ENGLISH_CORRECT', 5, 'gems', 10, 'english'),
(14, 'Explorer', 'Complete 2 quests', 'QUEST_COUNT', 2, 'gems', 12, 'all'),
(15, 'Streak Builder', 'Reach a 3-day streak', 'STREAK', 3, 'gems', 12, 'all'),
(16, 'Quick Thinker', 'Answer 10 questions', 'QUESTIONS_ANSWERED', 10, 'gems', 10, 'all'),
(17, 'Precision', 'Get 3 perfect answers', 'PERFECT_ANSWERS', 3, 'gems', 12, 'all'),
(18, 'SST Scholar', 'Get 5 SST answers right', 'SST_CORRECT', 5, 'gems', 10, 'sst'),
(19, 'Curious Mind', 'Answer 8 correctly', 'CORRECT_ANSWERS', 8, 'gems', 10, 'all'),
(20, 'Milestone 20', 'Complete 2 quests', 'QUEST_COUNT', 2, 'gems', 15, 'all'),
(21, 'Math Climber', 'Get 6 math right', 'MATH_CORRECT', 6, 'gems', 12, 'math'),
(22, 'Experiment', 'Get 6 science right', 'SCIENCE_CORRECT', 6, 'gems', 12, 'science'),
(23, 'Bookworm', 'Get 6 English right', 'ENGLISH_CORRECT', 6, 'gems', 12, 'english'),
(24, 'Map Reader', 'Get 6 SST right', 'SST_CORRECT', 6, 'gems', 12, 'sst'),
(25, 'Answer Machine', 'Answer 12 questions', 'QUESTIONS_ANSWERED', 12, 'gems', 12, 'all'),
(26, 'Sharp Mind', 'Get 4 perfect answers', 'PERFECT_ANSWERS', 4, 'gems', 14, 'all'),
(27, 'Triple Quest', 'Complete 3 quests', 'QUEST_COUNT', 3, 'gems', 15, 'all'),
(28, 'Week Four', 'Answer 10 correctly', 'CORRECT_ANSWERS', 10, 'gems', 12, 'all'),
(29, 'Streak Fire', 'Reach a 5-day streak', 'STREAK', 5, 'gems', 15, 'all'),
(30, 'Month One!', 'Complete 3 quests', 'QUEST_COUNT', 3, 'gems', 20, 'all'),
(31, 'New Chapter', 'Answer 10 correctly', 'CORRECT_ANSWERS', 10, 'gems', 12, 'all'),
(32, 'Math Sprint', 'Get 7 math right', 'MATH_CORRECT', 7, 'gems', 14, 'math'),
(33, 'Lab Rat', 'Get 7 science right', 'SCIENCE_CORRECT', 7, 'gems', 14, 'science'),
(34, 'Wordsmith', 'Get 7 English right', 'ENGLISH_CORRECT', 7, 'gems', 14, 'english'),
(35, 'Time Traveler', 'Get 7 SST right', 'SST_CORRECT', 7, 'gems', 14, 'sst'),
(36, 'Perfectionist', 'Get 5 perfect answers', 'PERFECT_ANSWERS', 5, 'gems', 16, 'all'),
(37, 'Quiz Blitz', 'Answer 15 questions', 'QUESTIONS_ANSWERED', 15, 'gems', 14, 'all'),
(38, 'Quest Runner', 'Complete 3 quests', 'QUEST_COUNT', 3, 'gems', 16, 'all'),
(39, 'Accuracy', 'Answer 12 correctly', 'CORRECT_ANSWERS', 12, 'gems', 14, 'all'),
(40, 'Forty Days', 'Reach a 7-day streak', 'STREAK', 7, 'gems', 20, 'all'),
(41, 'Number Ninja', 'Get 8 math right', 'MATH_CORRECT', 8, 'gems', 16, 'math'),
(42, 'Atom Smasher', 'Get 8 science right', 'SCIENCE_CORRECT', 8, 'gems', 16, 'science'),
(43, 'Vocab Builder', 'Get 8 English right', 'ENGLISH_CORRECT', 8, 'gems', 16, 'english'),
(44, 'Globe Trotter', 'Get 8 SST right', 'SST_CORRECT', 8, 'gems', 16, 'sst'),
(45, 'Halfway Month', 'Complete 4 quests', 'QUEST_COUNT', 4, 'gems', 18, 'all'),
(46, 'Brain Warm', 'Answer 15 correctly', 'CORRECT_ANSWERS', 15, 'gems', 16, 'all'),
(47, 'Clean Sweep', 'Get 6 perfect answers', 'PERFECT_ANSWERS', 6, 'gems', 18, 'all'),
(48, 'Endurance', 'Answer 18 questions', 'QUESTIONS_ANSWERED', 18, 'gems', 16, 'all'),
(49, 'Math Grind', 'Get 9 math right', 'MATH_CORRECT', 9, 'gems', 18, 'math'),
(50, 'Half Century', 'Complete 4 quests', 'QUEST_COUNT', 4, 'gems', 25, 'all'),
(51, 'Science Push', 'Get 9 science right', 'SCIENCE_CORRECT', 9, 'gems', 18, 'science'),
(52, 'Reading Hour', 'Get 9 English right', 'ENGLISH_CORRECT', 9, 'gems', 18, 'english'),
(53, 'Civics Pro', 'Get 9 SST right', 'SST_CORRECT', 9, 'gems', 18, 'sst'),
(54, 'Streak Master', 'Reach a 10-day streak', 'STREAK', 10, 'gems', 25, 'all'),
(55, 'Sharp Shooter', 'Get 7 perfect answers', 'PERFECT_ANSWERS', 7, 'gems', 20, 'all'),
(56, 'Big Day', 'Answer 18 correctly', 'CORRECT_ANSWERS', 18, 'gems', 18, 'all'),
(57, 'Five Quests', 'Complete 5 quests', 'QUEST_COUNT', 5, 'gems', 22, 'all'),
(58, 'Math Attack', 'Get 10 math right', 'MATH_CORRECT', 10, 'gems', 20, 'math'),
(59, 'Discovery', 'Answer 20 questions', 'QUESTIONS_ANSWERED', 20, 'gems', 18, 'all'),
(60, 'Two Months!', 'Complete 5 quests', 'QUEST_COUNT', 5, 'gems', 25, 'all'),
(61, 'Science Ace', 'Get 10 science right', 'SCIENCE_CORRECT', 10, 'gems', 20, 'science'),
(62, 'Spelling Bee', 'Get 10 English right', 'ENGLISH_CORRECT', 10, 'gems', 20, 'english'),
(63, 'History Ace', 'Get 10 SST right', 'SST_CORRECT', 10, 'gems', 20, 'sst'),
(64, 'Flawless', 'Get 8 perfect answers', 'PERFECT_ANSWERS', 8, 'gems', 22, 'all'),
(65, 'Momentum', 'Answer 20 correctly', 'CORRECT_ANSWERS', 20, 'gems', 20, 'all'),
(66, 'Math Boss', 'Get 12 math right', 'MATH_CORRECT', 12, 'gems', 22, 'math'),
(67, 'Lab Master', 'Get 12 science right', 'SCIENCE_CORRECT', 12, 'gems', 22, 'science'),
(68, 'Quest Fever', 'Complete 5 quests', 'QUEST_COUNT', 5, 'gems', 22, 'all'),
(69, 'Answer Storm', 'Answer 22 questions', 'QUESTIONS_ANSWERED', 22, 'gems', 20, 'all'),
(70, 'Seventy Days', 'Reach a 14-day streak', 'STREAK', 14, 'gems', 30, 'all'),
(71, 'English Pro', 'Get 12 English right', 'ENGLISH_CORRECT', 12, 'gems', 22, 'english'),
(72, 'SST Master', 'Get 12 SST right', 'SST_CORRECT', 12, 'gems', 22, 'sst'),
(73, 'Laser Focus', 'Get 10 perfect answers', 'PERFECT_ANSWERS', 10, 'gems', 25, 'all'),
(74, 'Power Hour', 'Answer 22 correctly', 'CORRECT_ANSWERS', 22, 'gems', 22, 'all'),
(75, 'Six Quests', 'Complete 6 quests', 'QUEST_COUNT', 6, 'gems', 25, 'all'),
(76, 'Math Wizard', 'Get 14 math right', 'MATH_CORRECT', 14, 'gems', 24, 'math'),
(77, 'Scientist', 'Get 14 science right', 'SCIENCE_CORRECT', 14, 'gems', 24, 'science'),
(78, 'Linguist', 'Get 14 English right', 'ENGLISH_CORRECT', 14, 'gems', 24, 'english'),
(79, 'Geographer', 'Get 14 SST right', 'SST_CORRECT', 14, 'gems', 24, 'sst'),
(80, 'Eighty Days', 'Answer 25 correctly', 'CORRECT_ANSWERS', 25, 'gems', 25, 'all'),
(81, 'Blitz Mode', 'Answer 25 questions', 'QUESTIONS_ANSWERED', 25, 'gems', 22, 'all'),
(82, 'No Mistakes', 'Get 12 perfect answers', 'PERFECT_ANSWERS', 12, 'gems', 28, 'all'),
(83, 'Quest Beast', 'Complete 6 quests', 'QUEST_COUNT', 6, 'gems', 25, 'all'),
(84, 'Streak Legend', 'Reach a 21-day streak', 'STREAK', 21, 'gems', 35, 'all'),
(85, 'Math Hero', 'Get 15 math right', 'MATH_CORRECT', 15, 'gems', 25, 'math'),
(86, 'Bio Blast', 'Get 15 science right', 'SCIENCE_CORRECT', 15, 'gems', 25, 'science'),
(87, 'Story Time', 'Get 15 English right', 'ENGLISH_CORRECT', 15, 'gems', 25, 'english'),
(88, 'Civic Duty', 'Get 15 SST right', 'SST_CORRECT', 15, 'gems', 25, 'sst'),
(89, 'Answer King', 'Answer 28 correctly', 'CORRECT_ANSWERS', 28, 'gems', 25, 'all'),
(90, 'Quarter One!', 'Complete 7 quests', 'QUEST_COUNT', 7, 'gems', 30, 'all');
